sudo: false
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - sudo apt-get install -y texlive texlive-latex-extra graphviz dvipng
install:
  - pip install tox-travis codecov
script: 
  - tox
  - ls -l .coverage
  - codecov
  - python3 setup.py sdist bdist_wheel
deploy:
  provider: pypi
  edge: true
  on:
    tags: true
  distributions: "sdist bdist_wheel" 
  skip_existing: true
