sudo: false
language: python
python:
  - "3.6"
  - "3.7"
before_install:
  - sudo apt-get install -y texlive texlive-latex-extra graphviz dvipng
install:
  - pip install tox-travis codecov
script: 
  - tox
  - ls -l .coverage
  - codecov
  - |
    if [[ $TRAVIS_TAG ]]; then
        python3 -m pip install twine
        python3 setup.py sdist bdist_wheel
        twine upload dist/mumot-*
    fi
